steps:
  - name: ubuntu
    entrypoint: bash
    args:
      - '-c'
      - |
        apt update
        apt install python3 python3-pip -y
        pip3 install poetry
        poetry export >| requirements.txt

  - name: ubuntu
    entrypoint: bash
    args:
      - '-c'
      - |
        printenv >| .env
    env:
      - 'SECRET_KEY=${_SECRET_KEY}'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'REDIS_URL=${_REDIS_URL}'
      - 'TYPESENSE_API_KEY=${_TYPESENSE_API_KEY}'
      - 'TYPESENSE_HOST=${_TYPESENSE_HOST}'

  - name: python
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt", "--user" ]

  - name: python
    entrypoint: python
    args: [ "manage.py", "collectstatic", "--noinput" ]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy", "--appyaml=infra/app.yaml" ]
