ALT_TAG = "//div[@class='media-name__alt']/text()"
YEAR_TAG = "//div[contains(@class, 'media-info-list__title') and contains(., 'Год релиза')]/following-sibling::*/text()"
GENRES_TAG = "//a[contains(@class, 'media-tag-item')]/text()"
DESCRIPTION_TAG = "//meta[@itemprop='description']/@content"
RATING_TAG = "//div[@class='media-rating__value']/text()"
CATEGORIES_TAG = "//div[contains(@class, 'media-info-list__title') and contains(., 'Тип')]/following-sibling::*/text()"
AUTHORS_TAG = "//div[contains(@class, 'media-info-list__title') and contains(., 'Автор')]/following-sibling::*/a/text()"
ILLUSTRATORS_TAG = "//div[contains(@class, 'media-info-list__title') and contains(., 'Художник')]/following-sibling::*/a/text()"
TRANSLATORS_TAG = "//div[@class='team-list-item__name']/text()"
