services:
  web_dev:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    expose:
      - 8000
    environment:
      - DEBUG
      - ALLOWED_HOSTS
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-sora}
      - SECRET_KEY=${SECRET_KEY:-DevServer}
      # Static
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_URL=redis://redis:6379
      - TYPESENSE_HOST=typesense
    ports:
      - "${PORT:-8888}:8000"
    volumes:
      - ./:/app
      - sora_poetry:/home/sora/.cache/pypoetry
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8000/api/health" ]
      interval: 5s
      timeout: 5s

  rq:
    image: backend_web_dev
    command: poetry run rq -A manga_reader worker -l INFO
    environment:
      - DEBUG
      - PROXY
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-sora}
      - SECRET_KEY=${SECRET_KEY:-DevServer}
      - REDIS_URL=redis://redis:6379
      - TYPESENSE_HOST=typesense
    volumes:
      - ./:/app
      - sora_poetry:/home/sora/.cache/pypoetry
    depends_on:
      - web_dev

volumes:
  sora_poetry: