# Generated by Django 3.2.6 on 2021-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcontrol',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taskcontrol',
            old_name='task_status',
            new_name='status',
        ),
    ]
