# Generated by Django 3.1 on 2021-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210822_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskControl',
        ),
    ]
