# Generated by Django 3.2.3 on 2021-05-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20210413_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='illustrator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={},
        ),
        migrations.AlterModelOptions(
            name='screenwriter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={},
        ),
    ]
