# Generated by Django 3.2.3 on 2021-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0003_auto_20210529_0806"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manga",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="manga",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="manga",
            name="self_url",
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
