# Generated by Django 3.2.3 on 2021-06-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0009_auto_20210616_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskControl',
        ),
    ]
