# Generated by Django 3.2.3 on 2021-06-22 13:19

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models
from django.db.migrations.operations.fields import AlterField


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0010_delete_taskcontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='self_url',
            new_name='source_url',
        ),
        migrations.AlterField(
            model_name='manga',
            name='source_url',
            field=models.URLField(default=1, max_length=2000, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonRelatedToManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.TextField(choices=[('author', 'Author'), ('illustrator', 'Illustrator'), ('screenwriter', 'Screenwriter'), ('translator', 'Translator')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='person',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='technical_params',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
        migrations.AddField(
            model_name='personrelatedtomanga',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='parse.manga'),
        ),
        migrations.AddField(
            model_name='personrelatedtomanga',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='parse.person'),
        ),
        migrations.AddField(
            model_name='manga',
            name='people_related',
            field=models.ManyToManyField(related_name='mangas', through='parse.PersonRelatedToManga', to='parse.Person'),
        ),
    ]
