# Generated by Django 3.2.3 on 2021-06-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0011_auto_20210622_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personrelatedtomanga',
            name='created',
        ),
        migrations.RemoveField(
            model_name='personrelatedtomanga',
            name='modified',
        ),
    ]
