# Generated by Django 3.2.3 on 2021-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0011_auto_20210618_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='technical_params',
        ),
        migrations.AddField(
            model_name='manga',
            name='rss_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
