# Generated by Django 3.2.3 on 2021-06-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0012_auto_20210622_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parse.person',),
        ),
        migrations.AlterField(
            model_name='personrelatedtomanga',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='parse.manga'),
        ),
        migrations.AlterField(
            model_name='personrelatedtomanga',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_relations', to='parse.person'),
        ),
    ]
