# Generated by Django 3.2.3 on 2021-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0013_auto_20210623_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='image_url',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
