# Generated by Django 3.2.3 on 2021-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0014_auto_20210623_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='chapters',
            new_name='volumes',
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='manga',
            name='thumbnail',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
