# Generated by Django 3.2.3 on 2021-06-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0015_auto_20210623_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='updated_chapters',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='updated_detail',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='rss_url',
            field=models.URLField(blank=True, null=True, max_length=2000),
        ),

    ]
