# Generated by Django 3.2.3 on 2021-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0015_auto_20210623_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
