# Generated by Django 3.2.3 on 2021-06-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0016_auto_20210618_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField(max_length=2000)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='volumes',
        ),
        migrations.CreateModel(
            name='VolumesRelatedToManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.manga')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='volumes',
            field=models.ManyToManyField(through='parse.VolumesRelatedToManga', to='parse.Chapter'),
        ),
    ]
