# Generated by Django 3.2.3 on 2021-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0019_rename_volumes_manga_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='parse.Category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='parse.Chapter'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='parse.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='manga',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
