# Generated by Django 3.2.3 on 2021-07-27 11:40

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0020_auto_20210727_2035"),
    ]

    operations = [
        migrations.RunSQL("UPDATE parse_manga SET rating = rating / 2 WHERE rating > 5;"),
    ]
