# Generated by Django 3.2.3 on 2021-07-27 11:40

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def convert_readmanga_rating(apps, schema_editor):
    Manga = apps.get_model("parse", "Manga")
    db_alias = schema_editor.connection.alias

    mangas = Manga.objects.using(db_alias).filter(source_url__contains="readmanga.live")
    for manga in mangas:
        if manga.rating > 5.0:
            manga.rating = round(manga.rating / 2, 2)

    Manga.objects.using(db_alias).bulk_update(mangas, ["rating"])


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0020_auto_20210727_2035"),
    ]

    operations = [
        migrations.RunPython(convert_readmanga_rating, reverse_code=RunPython.noop),
    ]
