# Generated by Django 3.2.3 on 2021-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0021_change_rating_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['popularity']},
        ),
        migrations.AddField(
            model_name='manga',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
