# Generated by Django 3.1 on 2021-08-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0022_auto_20210831_1152'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE parse_manga SET " \
                "source_url = REPLACE(source_url, 'readmanga.live', 'readmanga.io'), " \
                "rss_url = REPLACE(rss_url, 'readmanga.live', 'readmanga.io')"
        ),
    ]
