# Generated by Django 3.1 on 2021-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0023_readmanga_live_to_io'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.FloatField(),
        ),
    ]
