# Generated by Django 3.1 on 2021-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0026_auto_20211112_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
