# Generated by Django 3.2 on 2021-04-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_auto_20210310_0728"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
