# Generated by Django 3.2 on 2021-04-12 14:32

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import apps.readmanga_parser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="author_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="category_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="genre_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Illustrator",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="illustrator_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ScreenWriter",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="screenwriter_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Translator",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="translator_name")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="manga_name")),
                (
                    "self_url",
                    models.URLField(max_length=1000, unique=True, verbose_name="manga_url"),
                ),
                ("description", models.TextField(verbose_name="manga_description")),
                ("status", models.TextField(blank=True, null=True, verbose_name="status")),
                ("year", models.TextField(blank=True, null=True, verbose_name="year")),
                ("image_url", models.URLField(default="", verbose_name="image_url")),
                (
                    "chapters",
                    models.JSONField(default=dict),
                ),
                ("technical_params", models.JSONField(default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mangas",
                        to="readmanga_parser.author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(related_name="mangas", to="readmanga_parser.Category"),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="mangas", to="readmanga_parser.Genre"),
                ),
                (
                    "illustrators",
                    models.ManyToManyField(
                        related_name="mangas", to="readmanga_parser.Illustrator"
                    ),
                ),
                (
                    "screenwriters",
                    models.ManyToManyField(
                        related_name="mangas", to="readmanga_parser.ScreenWriter"
                    ),
                ),
                (
                    "translators",
                    models.ManyToManyField(related_name="mangas", to="readmanga_parser.Translator"),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
    ]
