# Generated by Django 3.1.7 on 2021-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image_url',
            field=models.TextField(default='', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='year',
            field=models.TextField(blank=True, null=True, verbose_name='year'),
        ),
    ]
