# Generated by Django 3.1.7 on 2021-03-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0002_auto_20210328_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='readmanga_parser.author'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='mangas', to='readmanga_parser.Category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='translators',
            field=models.ManyToManyField(blank=True, null=True, related_name='mangas', to='readmanga_parser.Translator'),
        ),
    ]
