# Generated by Django 3.1.7 on 2021-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0003_auto_20210328_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='translators',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Translator'),
        ),
    ]
