# Generated by Django 3.1.7 on 2021-03-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0004_auto_20210328_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
