# Generated by Django 3.1.7 on 2021-03-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0004_auto_20210328_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='technical_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
