# Generated by Django 3.1.7 on 2021-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0005_manga_technical_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='title',
        ),
        migrations.AddField(
            model_name='manga',
            name='name',
            field=models.TextField(db_index=True, default='no title', unique=True, verbose_name='manga_name'),
            preserve_default=False,
        ),
    ]
