# Generated by Django 3.2.3 on 2021-06-07 19:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0006_manga_alt_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('person_role', models.CharField(choices=[('Illustrator', 'Illustrator'), ('SCREENWRITER', 'Screenwriter'), ('TRANSLATOR', 'Translator')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='manga',
            name='illustrators',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='screenwriters',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='translators',
        ),
        migrations.DeleteModel(
            name='Illustrator',
        ),
        migrations.DeleteModel(
            name='ScreenWriter',
        ),
        migrations.DeleteModel(
            name='Translator',
        ),
        migrations.AddField(
            model_name='personrole',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='readmanga_parser.manga'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='readmanga_parser.person'),
        ),
    ]
