# Generated by Django 3.1.7 on 2021-04-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0006_auto_20210330_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='self_url',
            field=models.URLField(default='', max_length=1000, verbose_name='manga_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_url',
            field=models.URLField(default='', verbose_name='image_url'),
        ),
    ]
