# Generated by Django 3.2.3 on 2021-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0007_auto_20210607_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.BooleanField(default=False)),
                ('task_name', models.CharField(max_length=255)),
            ],
        ),
    ]
