# Generated by Django 3.1.7 on 2021-04-04 06:55

import apps.readmanga_parser.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0008_auto_20210401_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(unique=True, verbose_name='illustrator_name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScreenWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(unique=True, verbose_name='screenwriter_name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(apps.readmanga_parser.models.ReprMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangas', to='readmanga_parser.author'),
        ),
        migrations.AddField(
            model_name='manga',
            name='illustrators',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Illustrator'),
        ),
        migrations.AddField(
            model_name='manga',
            name='screenwriters',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.ScreenWriter'),
        ),
    ]
