# Generated by Django 3.2.3 on 2021-06-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0008_taskcontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskControl',
        ),
    ]
