# Generated by Django 3.1.7 on 2021-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0009_auto_20210404_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.TextField(verbose_name='manga_name'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='self_url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='manga_url'),
        ),
    ]
