# Generated by Django 3.2.3 on 2021-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0009_delete_taskcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
