# Generated by Django 3.1.7 on 2021-03-21 02:53

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', 'hstore_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
