# Generated by Django 3.1.7 on 2021-03-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(unique=True, verbose_name='author_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(unique=True, verbose_name='genre_name'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.TextField(verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.TextField(unique=True, verbose_name='translator_name'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
