# Generated by Django 3.1.7 on 2021-03-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0002_auto_20210309_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='year',
            field=models.TextField(default=None, verbose_name='year'),
            preserve_default=False,
        ),
    ]
