# Generated by Django 3.1.7 on 2021-03-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0004_auto_20210310_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='authors',
        ),
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='readmanga_parser.author'),
            preserve_default=False,
        ),
    ]
