# Generated by Django 3.1.7 on 2021-03-10 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0005_auto_20210310_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='author',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='genre',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='manga',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='translator',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translator',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='readmanga_parser.author'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='translators',
            field=models.ManyToManyField(related_name='mangas', to='readmanga_parser.Translator'),
        ),
    ]
