# Generated by Django 3.1.7 on 2021-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0006_auto_20210310_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.TextField(db_index=True, unique=True, verbose_name='manga_title'),
        ),
    ]
