# Generated by Django 3.1.7 on 2021-03-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0008_manga_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
