# Generated by Django 3.1.7 on 2021-03-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmanga_parser', '0009_auto_20210320_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='photo_url',
            new_name='image_url',
        ),
    ]
