# Generated by Django 4.1.1 on 2022-10-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_options_alter_manga_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='alt_title',
        ),
        migrations.AddField(
            model_name='manga',
            name='identifier',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
