# Generated by Django 4.1.3 on 2022-11-08 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0006_rename_rss_url_manga_chapters_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savelist",
            unique_together=set(),
        ),
        # It's a PostgreSQL 15 feature
        # https://www.postgresql.org/docs/15/release-15.html#id-1.11.6.5.5.3.4
        migrations.RunSQL(
            'CREATE UNIQUE INDEX "save_list_user_name_unique" ON '
            '"manga_savelist" ("user_id", "session", "name") NULLS NOT DISTINCT;',
            reverse_sql='DROP INDEX "save_list_user_name_unique";',
        ),
    ]
