# Generated by Django 4.1.3 on 2022-11-21 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manga", "0008_alter_category_options_alter_savelist_user_bookmark_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="bookmark_not_both_null",
        ),
        migrations.RemoveConstraint(
            model_name="savelist",
            name="not_both_null",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="session",
        ),
        migrations.RemoveField(
            model_name="savelist",
            name="session",
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chapter",
            name="manga",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="manga.manga",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savelist",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
