# Generated by Django 4.1.3 on 2022-11-21 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manga", "0009_remove_bookmark_bookmark_not_both_null_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savelist",
            unique_together={("user", "name")},
        ),
    ]
