name: Lint

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4.1.0
        id: python-setup
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: steps.python-setup.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint
        run: make check

