name: Lint

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: dhvcc/python-poetry-setup@v1
        with:
          python-version: 3.8.1

      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        if: steps.poetry-cache-test.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Lint
        run: |
          poetry run pre-commit run --all-files

